### ISSUE TITLE
Reverse transforms

### ISSUE THREAD

**Issue by GeeWee** [transform-it/transform-www#11]
This is a really cool project. I'm wondering what the prospects are for doing reverse transforms, or converting between e.g. PropTypes to typescript interfaces (which would enable automatic typing generation for React components that have PropTypes)
Is this something that this codebase could support or is it mainly geared towards 1-way transformations?

**Comment by ritz078** [comment]
There can be two types of reverse transforms.

- PropTypes to flow/typescript (in scope of this project)
- Proptypes/flow/interface to dummy JSON data (a separate project maybe)

But before implementing the first one, I would like to create a generic module that can handle flow, typescript and similar schemas.

**Comment by morajabi** [comment]
I think it would be better to have a unified language (something like ASTs) to convert everything into it and then transform it to the other. This approach makes it possible to user choose which one (JSON, TS/Flow, Mongoose) to convert to and which one to convert from.

Anyway, it's just an idea.

**Comment by GeeWee** [comment]
I think the unified language is a good idea!

**Comment by ritz078** [comment]
Its a great idea but I am not sure about the use case. Most of the times if you want to convert from A to B, you would want to make that change directly in the code.

For example - 
If you want to convert your codebase from PropTypes to flow, you would want to make those changes either by manually copy pasting or running a codemod.

I would love to hear your suggestions and I am truly up for a unified tool using AST that converts from A to B. But we need to make sure if a lot of people need it and are we solving a real problem with this ?

One use case that I have in mind
**npm module** - This totally seems feasible so that browser extensions can be made on top of that. It can be done even using the current transforms but ASTs will be cooler. Anyways I will really love a hand in that.

**Comment by GeeWee** [comment]
Imagine if you'd write your components in typescript, then you could automatically convert the interfaces into PropTypes for consumption by anyone not using typescript, or you could automatically create flow types from your PropTypes

**Comment by ritz078** [comment]
What you are talking about is codemods. In that case you need the to take the whole code into account. For example : It won't contain only propTypes . There will be some javascript code too. I guess there are already codemods available and that will just be a duplication of effort ?

What do you think ?

**Comment by GeeWee** [comment]
There's no (popular) codemods afaik that deal with flow or typescript. But in my opinion the end game is definitely a codemod, but this could work as a nice stepping stone, and I could definitely see me using it manually on my projects at first

**Comment by ritz078** [comment]
Yes that is a great concept but not in scope of this project but that is a great idea for a new project. This project is more about babel transforms and codemods will be more about jscodeshift. I will research on this when I have time.
